distributable:
  url: https://registry.npmjs.org/nx/-/nx-{{version}}.tgz
  strip-components: 1

display-name: nx.dev

versions:
  github: nrwl/nx/releases

provides:
  - bin/nx

dependencies:
  nodejs.org: ^18

build:
  dependencies:
    npmjs.com: ^10
  script:
    - npm i $ARGS .
  env:
    ARGS:
      - --global
      - --install-links
      - --prefix={{prefix}}

test:
  script: |
    nx --version

